---
- name: Render docker-compose.yml
  block:
    - name: Create deployment dir
      file:
        path: "{{ deploy_path }}" 
        state: directory
        mode: '0755'

    - name: Render template
      template:
        src: docker-compose.yml.j2
        dest: "{{ deploy_path }}/docker-compose.yml"
        mode: '0644'
  tags:
    - render-docker-compose

- name: Start web app
  block:
    - name: Start docker-compose
      community.docker.docker_compose_v2:
        project_src: "{{ deploy_path }}" 
        state: present
  tags:
    - start-web-app

- include_tasks: 0-wipe.yml
  when: web_app_full_wipe | bool
  tags: 
    - web_app_full_wipe
